<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Open Blog '.$this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
            ->appendName('viewport',
                'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Tell the browser to be responsive to screen width -->

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath().'/img/favicon.ico'))
            ->appendStylesheet('/templates/admin-lte/bootstrap/css/bootstrap.min.css')
            ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
            ->appendStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
            ->appendStylesheet('/templates/admin-lte/dist/css/AdminLTE.min.css')
            ->appendStylesheet('/templates/admin-lte/dist/css/skins/_all-skins.min.css')
            ->appendStylesheet('/templates/admin-lte/plugins/iCheck/flat/blue.css')
            ->appendStylesheet('/templates/admin-lte/plugins/morris/morris.css')
            ->appendStylesheet('/templates/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css')
            ->appendStylesheet('/templates/admin-lte/plugins/datepicker/datepicker3.css')
            ->appendStylesheet('/templates/admin-lte/plugins/daterangepicker/daterangepicker-bs3.css')
            ->appendStylesheet('/templates/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
        ;
        ?>

        <?php
        $this->headScript()
            ->appendFile('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
                'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
                'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <?php echo $this->partial('partial//header-admin'); ?>

            <!-- Left side column. contains the logo and sidebar -->
            <?php echo $this->partial('partial/navigation-admin'); ?>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->title; ?>
                        <small><?php echo $this->subTitle; ?></small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <section class="content">
                    <?php echo $this->content; ?>
                </section>
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.3.2
                </div>
                <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
                reserved.
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Create the tabs -->
                <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
                    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- Home tab content -->
                    <div class="tab-pane" id="control-sidebar-home-tab">
                        <h3 class="control-sidebar-heading">Recent Activity</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript::;">
                                    <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                                        <p>Will be 23 on April 24th</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <i class="menu-icon fa fa-user bg-yellow"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                                        <p>New phone +1(800)555-1234</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                                        <p>nora@example.com</p>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <i class="menu-icon fa fa-file-code-o bg-green"></i>

                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                                        <p>Execution time 5 seconds</p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <!-- /.control-sidebar-menu -->

                        <h3 class="control-sidebar-heading">Tasks Progress</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript::;">
                                    <h4 class="control-sidebar-subheading">
                                        Custom Template Design
                                        <span class="label label-danger pull-right">70%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <h4 class="control-sidebar-subheading">
                                        Update Resume
                                        <span class="label label-success pull-right">95%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <h4 class="control-sidebar-subheading">
                                        Laravel Integration
                                        <span class="label label-warning pull-right">50%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript::;">
                                    <h4 class="control-sidebar-subheading">
                                        Back End Framework
                                        <span class="label label-primary pull-right">68%</span>
                                    </h4>

                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <!-- /.control-sidebar-menu -->

                    </div>
                    <!-- /.tab-pane -->
                    <!-- Stats tab content -->
                    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
                    <!-- /.tab-pane -->
                    <!-- Settings tab content -->
                    <div class="tab-pane" id="control-sidebar-settings-tab">
                        <form method="post">
                            <h3 class="control-sidebar-heading">General Settings</h3>

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Report panel usage
                                    <input type="checkbox" class="pull-right" checked>
                                </label>

                                <p>
                                    Some information about this general settings option
                                </p>
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Allow mail redirect
                                    <input type="checkbox" class="pull-right" checked>
                                </label>

                                <p>
                                    Other sets of options are available
                                </p>
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Expose author name in posts
                                    <input type="checkbox" class="pull-right" checked>
                                </label>

                                <p>
                                    Allow the user to show his name in blog posts
                                </p>
                            </div>
                            <!-- /.form-group -->

                            <h3 class="control-sidebar-heading">Chat Settings</h3>

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Show me as online
                                    <input type="checkbox" class="pull-right" checked>
                                </label>
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Turn off notifications
                                    <input type="checkbox" class="pull-right">
                                </label>
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Delete chat history
                                    <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                                </label>
                            </div>
                            <!-- /.form-group -->
                        </form>
                    </div>
                    <!-- /.tab-pane -->
                </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>

        <?php
        echo $this->headScript()
            ->appendFile('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
                'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
                'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile('/templates/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js',
                'text/javascript')
            ->appendFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js',
                'text/javascript')
            ->appendFile('/scripts/main.js', 'text/javascript')
            ->appendFile('/templates/admin-lte/bootstrap/js/bootstrap.min.js',
                'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/morris/morris.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/sparkline/jquery.sparkline.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/knob/jquery.knob.js',
                'text/javascript')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/daterangepicker/daterangepicker.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/datepicker/bootstrap-datepicker.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/slimScroll/jquery.slimscroll.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/plugins/fastclick/fastclick.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/dist/js/app.min.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/dist/js/pages/dashboard.js',
                'text/javascript')
            ->appendFile('/templates/admin-lte/dist/js/demo.js',
                'text/javascript')
        //----------------------------------------------------------------------

        ;
        ?>


    </body>
</html>
